### ISSUE TITLE
inform the user about log levels when deployment fails

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#166]
e.g.
```
~/binaris $ cd user/
~/binaris/user $ bn deploy
bn: Failed to deploy function nappyneck
```

This is practicaly useless as an error message...
At the very minimum explain to the user how to increase the log level.

**Comment by rylandg** [comment]
@lavie As a starting point what about https://github.com/binaris/binaris/commit/e1968e4de440a933f7c4b1e2bd72fabfc8fe8507. The text is negotiable (clearly...) but I'm more interested in the expected user interaction.

**Comment by lavie** [comment]
Good stuff.

**Comment by michaeladda** [comment]
The debug tip now shows everywhere. A bit too pervasive imho, but you can no longer miss the log levels.
