### ISSUE TITLE
returning an error string in callback should print the error when invoked by CLI

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#185]
I wrote a function that just called `cb("intentional error", {});` and I expected to see this error printed out when I did `bn invoke`. I saw `500 - Internal Server Error` instead. The logs showed nothing.

Also, it is unclear what happens if I pass a non-null error and also a 200 status code in the 2nd param of the callback. Who wins?

And finally, all uncaught js exceptions should also be conveyed when invoking with the CLI. The error message should be printed out (in red) with a non-zero exit code.

**Comment by rylandg** [comment]
This now works as intended.
