### ISSUE TITLE
No `--key` argument in `bn login`

### ISSUE THREAD

**Issue by adamatan** [binaris/binaris#212]
# The problem
`bn login` is missing the `--key` argument, and only accepts the user input via an interactive prompt.

I think that all `bn` commands should be able to run within a script (a `Dockerfile` would be a good example).

# Suggested Solution

## Precedence rules
1. Explicit API key given with a `--api-key` argument
2. API Key found in an environment variable (`BINARIS_API_KEY` or `BINARIS_APIKEY`)
3. API Key from `*~/.binaris`
4. Prompt the user (I seriously doubt it's even necessary - where would that be useful?)

**Comment by rylandg** [comment]
I'm closing this for now. If we want to resurrect it in the future anyone is free to do so.
