### ISSUE TITLE
bn log --since [ISO 8601]

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#215]

**Comment by lavie** [comment]
This is proving to be a sorely missing feature. Especially when combined with `-t` on a function that's been running for a while. Should be able to do `bn logs foo -t --since 1h`, or something equivalent. Otherwise you just sit there waiting for infinite logs to be piped out.

**Comment by lavie** [comment]
I just want to stress the urgency of this bug. It means that for any long-living function (e.g. someone spending days developing it, running it) `tail -f` is essentially unavailable, so you cannot see logs at all as you develop.

**Comment by rylandg** [comment]
This has been fixed by the logs rework.
