### ISSUE TITLE
Every user visible error message ought to be actionable

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#246]
e.g. 

```
~/binaris/functions/hello $ bn deploy hello
Could not connect to Binaris backend
```
This error message, while somewhat informative, does not tell the user what he can do about it. Is it his fault? Could he simply be disconnected from the internet? Is the binaris backend down?
A good error message will tell the user what he can do to get stuff done. Should he retry? If so, apologise for the unavailability and ask to retry. If there's no internet connection at all, the CLI can figure this out and advise accordingly ("Are you sure you have internet connectivity?"). 
This is a general developer UX point, not specific to `bn deploy`. We should strive to do our best to make errors more actionable.

**Comment by rylandg** [comment]
This is the mentality that we have adopted. Although not errors are actionable I feel comfortable closing this issue and relying on individual erroneous (punny) cases.
