### ISSUE TITLE
bn does not work with node 8.1.2, but the minimal version is set to 8.0.0

### ISSUE THREAD

**Issue by adamatan** [binaris/binaris#266]
I will try to reproduce it using a Dockerfile to pinpoint the correct minimum version.

**Comment by rylandg** [comment]
Can you be more specific with

> does not work

Is this an incompatibility between our syntax and updated node features?

**Comment by rylandg** [comment]
@adamatan any luck with this?

**Comment by rylandg** [comment]
Reopen if still valid. Closing for now.
