### ISSUE TITLE
bn commands only work from binaris.yml dir

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#294]
no reason the user should not be able to remove a function from any dir, as long as he specifies the name and the API key is available as envar.

This becomes a pain when you want to delete a function for which you no longer have the source dir for some reason. you then need to create some fake binaris.yml just to be able to delete the function.

**Comment by arielshaqed** [comment]
## Updated from `bn remove` to `bn` commands

This also means that I cannot read logs from Scoobie when it fails, denying me the ability to debug.

**Comment by rylandg** [comment]
@arielshaqed I've made this a non-issue in `scoobie` which I describe in the README.

`make func_logs funcName=runner since=1h`
This also handles the of prefixing the functions.

As for the CLI aspect I'm not sure this is behavior we want for all commands.

**Comment by rylandg** [comment]
https://github.com/binaris/binaris/pull/307
https://github.com/binaris/binaris/pull/318
https://github.com/binaris/binaris/pull/319
Handled for relevant commands
