### ISSUE TITLE
spec test job should run from clean ubuntu with node

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#296]
it should accept an option npm version for binaris package, and install the package on a clean ubuntu with node, as a new user would.

**Comment by rylandg** [comment]
Minus choosing the `binaris` version that's what it does. I wrote the test driver to create a fresh ubuntu container with a non-root NodeJS installation for each individual spec item. Being able to specify the version is a good idea.

**Comment by rylandg** [comment]
I'm closing this because I don't think it's valid.  If anything a different issue COULD be opened for allowing specific versions of the CLI to be tested with the spec. 

Currently we use the repo to bootstrap the testing spec and would need to change that quite a bit.
