### ISSUE TITLE
Container test helper hangs when bash crashes

### ISSUE THREAD

**Issue by bergundy** [binaris/binaris#311]
### Steps to reproduce:
Add a spec with a command which should crash bash, e.g: `exit 1` or `for x in 1 2; echo; done` (for crashing with an error message)

### Symptoms of bash crashing:
```js
this.dockerStream.on('end', () => { /* container has crashed */ });
```

### Proposed solution:
Abort test on crash and print stdout / stderr / return code so developer of test case knows what he did wrong, e.g:
```
 stdout: '',
  stderr: 'bash: line 1: syntax error near unexpected token `echo\'\nbash: line 1: `for x in 1 2; echo; done\'\n',
  exitCode: NaN }
```

**Comment by bergundy** [comment]
CC: @rylandg @lavie

**Comment by rylandg** [comment]
Should be initially solved here https://github.com/binaris/binaris/pull/320

**Comment by rylandg** [comment]
Fixed https://github.com/binaris/binaris/pull/320
