### ISSUE TITLE
commands fail silently because of bad api key

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#336]
If a non-existing API key is used for commands, often the result is just a seemingly healthy response that looks empty.

e.g.
`bn logs`, `bn list` - if the API key does not exist the result is just an empty printout. No word to the user about the api key problem.

**Comment by rylandg** [comment]
First portion fixed here https://github.com/binaris/binaris/pull/339

**Comment by rylandg** [comment]
Surprisingly the rest of this issue `bn logs` is actually due to a backend issue with authentication.

**Comment by vogre** [comment]
`bn logs` returns errors now.
