### ISSUE TITLE
allow passing data to bn perf

### ISSUE THREAD

**Issue by lavie** [binaris/binaris#344]
Currently bn perf is basically a GET operation without any additional params passed in (query, body or otherwise). This frequently frustrated me and forced me to use 3rd party tools to generate load, where a simple query param would have probably sufficed to get the job done.

**Comment by rylandg** [comment]
https://github.com/binaris/binaris/pull/352

**Comment by rylandg** [comment]
Added in https://github.com/binaris/binaris/pull/352
