### ISSUE TITLE
Unknown parameters should trigger a warning

### ISSUE THREAD

**Issue by adamatan** [binaris/binaris#368]
# What Happened

I have just wasted a few frustrating minutes for a silly:

    bn invoke createWebhook --date

instead of

    bn invoke createWebhook --data

typo.

# Desired Behaviour
Our CLI should either warn for unknown arguments (or fail completely, the same way `git` does) when facing unknown arguments.

**Comment by rylandg** [comment]
Here https://github.com/binaris/binaris/pull/372

**Comment by michaeladda** [comment]
already fixed
