### ISSUE TITLE
Binaris tests fail when output exceeds 4k (or 64k)

### ISSUE THREAD

**Issue by vogre** [binaris/binaris#374]
As seen in [ci](https://ci.binaris.io/blue/organizations/jenkins/gobinaris%2Fprecious/detail/master/5012/pipeline/223/).
Reproduced by a test that logs `'a'`*65535 and `'z'` with a test on output `a*z`.

**Comment by vogre** [comment]
Not really closed but worked around, the bug appears to be in dockerode not emitting more of the stdout.

**Comment by rylandg** [comment]
Oh boy, I'll look and see what real solutions we might have.

**Comment by arielshaqed** [comment]
# 😿
