### ISSUE TITLE
bn logs on sandbox realm returns an error

### ISSUE THREAD

**Issue by nirmash** [binaris/binaris#400]
bn logs for the sandbox realm (public functions, binaris@pre cli) returns: 
```Cannot destructure property `nextToken` of 'undefined' or 'null'.```

**Comment by arielshaqed** [comment]
Yeah, that's a horrible result.  Can you share the function on this bug, please?  (Easiest is to zip it up and "Attach files...", at the bottom of the Comment box.  Yes, it's a confusing UI.)

**Comment by michaeladda** [comment]
looks very similar to #384 
might be a duplicate. i suspect you didn't configure your endpoints manually, right? might be a log/logs issue again

**Comment by nirmash** [comment]
didn't do anything special. anything else I should try?

**Comment by michaeladda** [comment]
it seems this is indeed a logs vs log endpoint issue with the sandbox realm.
you can `export BINARIS_LOG_ENDPOINT=logs-sandbox.binaris.com` as a short term work around.

**Comment by nirmash** [comment]
Got it thanks!

**Comment by nirmash** [comment]
works now

**Comment by michaeladda** [comment]
fixed by #402
@nirmash you can upgrade your client and unexport the hack :-)
