### ISSUE TITLE
Logs new line formatting is broken

### ISSUE THREAD

**Issue by bergundy** [binaris/binaris#417]
* If no newline at the end of logs output, the accumulated line is not printed.
* When handling multiple log inputs (system messages, multiple invocations) we should add stop accumulating the line and print what we have.
* Request ID is present in the logs response but is not shown to the user.

**Comment by rylandg** [comment]
Hey, I don't mind taking this over if you can provide me some expected/current outputs.

**Comment by bergundy** [comment]
For the first point you need a log message that doesn't end with new line:
```json
[
  { "msg": "aaa", "time": "1999-12-31T23:59:59.999Z", "isErr": false, "reqID": "a94a5a42e69a579223d22a9896d1cb5e" }
]
```
Expected output:
```
[1999-12-31T23:59:59.999Z] <a94a5a42e69a579223d22a9896d1cb5e> aaa
```

For the second point:
```json
[
  { "msg": "aaa", "time": "1999-12-31T23:59:59.999Z", "isErr": false, "reqID": "a" },
  { "msg": "bbb", "time": "1999-12-31T23:59:59.999Z", "isErr": false, "reqID": "b" }
]
```
Expected output:
```
[1999-12-31T23:59:59.999Z] <a> aaa
[1999-12-31T23:59:59.999Z] <b> bbb
```

Third point is included in the 2 above.

Not exactly sure how to reproduce these in e2e tests so we might have to settle for unit tests.

There are 3 issues to discuss here:
1. How do we present the request ID in the logs, in the examples above I used `[time] <reqID> msg` format.
2. Do we print anything when we artificially break a log line? e.g: `␊`
3. Should we have a default format and allow the user to pass a format string - could be an advanced feature.

**Comment by bergundy** [comment]
I think this might not be relevant to the world anymore
