### ISSUE TITLE
Deploy print shouldn't use 'run-prod`

### ISSUE THREAD

**Issue by rylandg** [binaris/binaris#419]
I believe it's much cleaner to keep prod as `run.binaris.com`. We shouldn't have the user go to `run-prod.*` because it's less succinct and can also cause CORS issues such as in my demo.

```
Deployed function public_servePage
Invoke with one of:
  "bn invoke public_servePage"
  "curl https://run-prod.binaris.com/v2/run/********/public_servePage"
```

**Comment by michaeladda** [comment]
I think your system is somehow configured to use that endpoint.
Please check your `~/.binaris.yml` and `env | grep BINARIS`.
On my system both deploys work.
old style deploy:
```
Michaels-MacBook-Pro-4:func michael$ bn deploy hell8
Deployed function hell8
Invoke with one of:
  "bn invoke hell8"
  "curl https://run.binaris.com/v1/run/**********/hell8"
Michaels-MacBook-Pro-4:func michael$ 
```
new style restricted deploy:
```
Michaels-MacBook-Pro-4:func michael$ bn deploy hell8
Deployed function hell8
Invoke with one of:
  "bn invoke hell8"
  "curl -H X-Binaris-Api-Key:****** https://run.binaris.com/v2/run/111010011010/hell8"
```
and new style public deploy
```
Michaels-MacBook-Pro-4:func michael$ bn deploy public_hell8
Deployed function public_hell8
Invoke with one of:
  "bn invoke public_hell8"
  "curl https://run.binaris.com/v2/run/111010011010/public_hell8"
```
which also matches the behaviour I see in https://github.com/binaris/binaris/blob/master/sdk/config.js regarding default endpoints.

**Comment by rylandg** [comment]
@michaeladda why did you close this issue without giving me a chance to respond? 

The issue exists when the key given to login if prefaced with the realm ie `prod-**********`. As you can see from the `forceRealm` code, if a realm exists in the config we then forcibly change the endpoints to be in the previously described format. The fact that users interact with `sandbox` and a realm IS required tells me this will most likely happen again.

**Comment by rylandg** [comment]
I now understand the core problem. I didn't understand that the `realm` prefix wasn't needed for `prod` initially (because I made my first account on sandbox) and therefore assumed a prefix was required. Indeed we aren't handing out keys with `prod-` prefix.

The remaining problem is that we can print out a different endpoint to the user compared to what we actually use internally. I still fail to see the value in this.

**Comment by michaeladda** [comment]
so, now that we all agree the cli does not print `run-prod` i'm closing this issue.
if you have a real example of endpoint mismatch please open a new issue with the example.
