### ISSUE TITLE
binaris-as-a-module patches Object

### ISSUE THREAD

**Issue by arielshaqed** [binaris/binaris#437]
It uses module `loadtest`, which uses module `prototypes`, which patches methods into `Object`.  This makes using Jest hard (it separates packages), and means that you're essentially getting a random version of the patched methods from `prototypes`.

**Comment by rylandg** [comment]
I'm failing to understand how this would interfere with `Jest`. After looking at the `prototypes` package it seems that they inject the additional functionality without disrupting too much.

**Comment by rylandg** [comment]
More info https://github.com/alexfernandez/loadtest/issues/159

**Comment by arielshaqed** [comment]
It doesn't work with Jest.  Jest load packages  separately, and you don't see the effect of `prototypes`, which means nothing works.

Generally, patching the global package is an odious practice.  It makes the binaris SDK hard to use with Jest.

**Comment by rylandg** [comment]
Can you please link me to a reference regarding this part 

> Jest load packages separately

I'm failing to find any literature when I consult Google.

And again it seems that the `prototype` people are aware of the potential wide-spread implications of patching `Object` and have done it in the safest possible way (not free of danger, just best practices)

**Comment by vogre** [comment]
Issue in Jest: https://github.com/facebook/jest/issues/4940#issuecomment-346557115 - it also suggests the workaround by using `jest.mock` which works, but is somewhat obscure.

**Comment by arielshaqed** [comment]
This
> Generally, patching the global package is an odious practice. It makes the binaris SDK hard to use with Jest.
will turn into a fairly useless fight.  (While I'm obviously right,) I'd prefer to avoid arguing the case.

I _will_ say that the current `binaris` SDK doesn't work with Jest.  Note that `prototypes` is an indirect dependency; the problem is that we use `loadtest`.  I think it might work if we avoided requiring `loadtest` in the SDK, at least by default.

**Comment by arielshaqed** [comment]
We might now close this.  I'd label "WONTFIX" / "INVALID", but I no longer have permissions on this project.
