### ISSUE TITLE
Support multiple functions per one binaris.yml file

### ISSUE THREAD

**Issue by michaeladda** [binaris/binaris#87]
The default behaviour when a function name is not given should be to loop on all functions or print an error asking for a specific function.
`bn deploy` should deploy all functions.
`bn deploy foo` should deploy only `foo`.
`bn invoke` should error and require a function name.

**Comment by rylandg** [comment]
This is not the current path we've taken. If this becomes a relevant topic of discussion again, let's reopen it.
